version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/server
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://red-ctrqj03tq21c7390m9l0:6379
    depends_on:
      - redis

  redis:
    image: redis:7.0.12
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001" # RedisInsight's default port
    depends_on:
      - redis
    environment:
      - REDIS_INSIGHT_FEATURE_FLAG_HOME_DATABASE=true

volumes:
  redis-data:
